apiVersion: argoproj.io/v1alpha1
status: {}
kind: Workflow
metadata:
  generateName: nevermined-compute-
spec:
  hostNetwork: true
  entrypoint: start
  templates:
  - name: xain-fl
    inputs:
      parameters:
        - name: config
        - name: command
    container:
      name: 'xain-fl'
      image: keykoio/xain-fl:latest
      imagePullPolicy: IfNotPresent
      command: ["{{inputs.parameters.command}}"]
      args: ["-c", "{{inputs.parameters.config}}"]

  - name: start
    dag:
      tasks:
        - name: coordinator
          template: xain-fl
          arguments:
            parameters:
            - name: command
              value: "coordinator"
            - name: config
              value: "/bin/config-coordinator.toml"
        - name: aggregator
          template: xain-fl
          arguments:
            parameters:
            - name: command
              value: "aggregator"
            - name: config
              value: "/bin/config-aggregator.toml"
